export default {
    LOADING: "LOADING",
    UPDATE_TOPS:"UPDATE_TOPS",
    UPDATE_LIST: "UPDATE_LIST",
    UPDATE_STORY: "UPDATE_STORY",
    UPDATE_STORY_INFO: "UPDATE_STORY_INFO",
    UPDATE_STORY_COMMENT:"UPDATE_STORY_COMMENT"

}