export default {
  LOADING: "LOADING",
  UPDATE_TOPS: "UPDATE_TOPS",
  UPDATE_LIST: "UPDATE_LIST",
  UPDATE_STORY_CONTENT: "UPDATE_STORY_CONTENT",
  UPDATE_STORY_ID: "UPDATE_STORY_ID",
  UPDATE_STORY_INFO: "UPDATE_STORY_INFO",
  UPDATE_STORY_COMMENT: "UPDATE_STORY_COMMENT"
};
